/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.KycVerif.Sdk;

public class KycVerifSdkEngine {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KycVerifSdkEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KycVerifSdkEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KYCDocumentsVerifSDKJNI.delete_KycVerifSdkEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static KycVerifSdkResult init(String jsonConfig, KycVerifSdkParallelDeliveryCallback parallelDeliveryCallback) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_init__SWIG_0(jsonConfig, KycVerifSdkParallelDeliveryCallback.getCPtr(parallelDeliveryCallback), parallelDeliveryCallback), true);
  }

  public static KycVerifSdkResult init(String jsonConfig) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_init__SWIG_1(jsonConfig), true);
  }

  public static KycVerifSdkResult init() {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_init__SWIG_2(), true);
  }

  public static KycVerifSdkResult deInit() {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_deInit(), true);
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer imageDataPtr, long imageWidthInSamples, long imageHeightInSamples, long imageStrideInSamples, int imageExifOrientation) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_process__SWIG_0(imageType.swigValue(), imageDataPtr, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples, imageExifOrientation), true);
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer imageDataPtr, long imageWidthInSamples, long imageHeightInSamples, long imageStrideInSamples) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_process__SWIG_1(imageType.swigValue(), imageDataPtr, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples), true);
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer imageDataPtr, long imageWidthInSamples, long imageHeightInSamples) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_process__SWIG_2(imageType.swigValue(), imageDataPtr, imageWidthInSamples, imageHeightInSamples), true);
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes, long uvPixelStrideInBytes, int exifOrientation) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_process__SWIG_3(imageType.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation), true);
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes, long uvPixelStrideInBytes) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_process__SWIG_4(imageType.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes), true);
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_process__SWIG_5(imageType.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes), true);
  }

  public static KycVerifSdkResult process(java.nio.ByteBuffer encodedDataPtr, long encodedDataSize) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_process__SWIG_6(encodedDataPtr, encodedDataSize), true);
  }

  public static int exifOrientation(java.nio.ByteBuffer jpegMetaDataPtr, long jpegMetaDataSize) {
    return KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_exifOrientation(jpegMetaDataPtr, jpegMetaDataSize);
  }

  public static KycVerifSdkResult requestRuntimeLicenseKey(boolean rawInsteadOfJSON) {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_0(rawInsteadOfJSON), true);
  }

  public static KycVerifSdkResult requestRuntimeLicenseKey() {
    return new KycVerifSdkResult(KYCDocumentsVerifSDKJNI.KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_1(), true);
  }

}
