/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.KycVerif.Sdk {

public enum KYC_VERIF_SDK_IMAGE_TYPE {
  KYC_VERIF_SDK_IMAGE_TYPE_RGB24,
  KYC_VERIF_SDK_IMAGE_TYPE_RGBA32,
  KYC_VERIF_SDK_IMAGE_TYPE_BGRA32,
  KYC_VERIF_SDK_IMAGE_TYPE_BGR24,
  KYC_VERIF_SDK_IMAGE_TYPE_NV12,
  KYC_VERIF_SDK_IMAGE_TYPE_NV21,
  KYC_VERIF_SDK_IMAGE_TYPE_YUV420P,
  KYC_VERIF_SDK_IMAGE_TYPE_YVU420P,
  KYC_VERIF_SDK_IMAGE_TYPE_YUV422P,
  KYC_VERIF_SDK_IMAGE_TYPE_YUV444P,
  KYC_VERIF_SDK_IMAGE_TYPE_Y
}

}
