/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.KycVerif.Sdk {

using System;
using System.Runtime.InteropServices;

public class KYCDocumentsVerifSDK {
  public static readonly int KYC_VERIF_SDK_VERSION_MAJOR = KYCDocumentsVerifSDKPINVOKE.KYC_VERIF_SDK_VERSION_MAJOR_get();
  public static readonly int KYC_VERIF_SDK_VERSION_MINOR = KYCDocumentsVerifSDKPINVOKE.KYC_VERIF_SDK_VERSION_MINOR_get();
  public static readonly int KYC_VERIF_SDK_VERSION_MICRO = KYCDocumentsVerifSDKPINVOKE.KYC_VERIF_SDK_VERSION_MICRO_get();
}

}
