/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.KycVerif.Sdk {

using System;
using System.Runtime.InteropServices;

public class KycVerifSdkParallelDeliveryCallback : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal KycVerifSdkParallelDeliveryCallback(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(KycVerifSdkParallelDeliveryCallback obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~KycVerifSdkParallelDeliveryCallback() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          KYCDocumentsVerifSDKPINVOKE.delete_KycVerifSdkParallelDeliveryCallback(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual void onNewResult(KycVerifSdkResult newResult) {
    KYCDocumentsVerifSDKPINVOKE.KycVerifSdkParallelDeliveryCallback_onNewResult(swigCPtr, KycVerifSdkResult.getCPtr(newResult));
  }

}

}
