/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.KycVerif.Sdk {

using System;
using System.Runtime.InteropServices;

public class KycVerifSdkResult : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal KycVerifSdkResult(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(KycVerifSdkResult obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~KycVerifSdkResult() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          KYCDocumentsVerifSDKPINVOKE.delete_KycVerifSdkResult(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public KycVerifSdkResult() : this(KYCDocumentsVerifSDKPINVOKE.new_KycVerifSdkResult__SWIG_0(), true) {
  }

  public KycVerifSdkResult(int code, string phrase, string json, uint numFaces) : this(KYCDocumentsVerifSDKPINVOKE.new_KycVerifSdkResult__SWIG_1(code, phrase, json, numFaces), true) {
  }

  public KycVerifSdkResult(int code, string phrase, string json) : this(KYCDocumentsVerifSDKPINVOKE.new_KycVerifSdkResult__SWIG_2(code, phrase, json), true) {
  }

  public KycVerifSdkResult(KycVerifSdkResult other) : this(KYCDocumentsVerifSDKPINVOKE.new_KycVerifSdkResult__SWIG_3(KycVerifSdkResult.getCPtr(other)), true) {
    if (KYCDocumentsVerifSDKPINVOKE.SWIGPendingException.Pending) throw KYCDocumentsVerifSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public int code() {
    int ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_code(swigCPtr);
    return ret;
  }

  public string phrase() {
    string ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_phrase(swigCPtr);
    return ret;
  }

  public string json() {
    string ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_json(swigCPtr);
    return ret;
  }

  public uint numVIZs() {
    uint ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_numVIZs(swigCPtr);
    return ret;
  }

  public bool isOK() {
    bool ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkResult_isOK(swigCPtr);
    return ret;
  }

}

}
