/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.KycVerif.Sdk {

using System;
using System.Runtime.InteropServices;

public class KycVerifSdkEngine : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal KycVerifSdkEngine(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(KycVerifSdkEngine obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~KycVerifSdkEngine() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          KYCDocumentsVerifSDKPINVOKE.delete_KycVerifSdkEngine(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public static KycVerifSdkResult init(string jsonConfig, KycVerifSdkParallelDeliveryCallback parallelDeliveryCallback) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_init__SWIG_0(jsonConfig, KycVerifSdkParallelDeliveryCallback.getCPtr(parallelDeliveryCallback)), true);
    return ret;
  }

  public static KycVerifSdkResult init(string jsonConfig) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_init__SWIG_1(jsonConfig), true);
    return ret;
  }

  public static KycVerifSdkResult init() {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_init__SWIG_2(), true);
    return ret;
  }

  public static KycVerifSdkResult deInit() {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_deInit(), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr imageDataPtr, uint imageWidthInSamples, uint imageHeightInSamples, uint imageStrideInSamples, int imageExifOrientation) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_0((int)imageType, imageDataPtr, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples, imageExifOrientation), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr imageDataPtr, uint imageWidthInSamples, uint imageHeightInSamples, uint imageStrideInSamples) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_1((int)imageType, imageDataPtr, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr imageDataPtr, uint imageWidthInSamples, uint imageHeightInSamples) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_2((int)imageType, imageDataPtr, imageWidthInSamples, imageHeightInSamples), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes, int exifOrientation) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_3((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_4((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes), true);
    return ret;
  }

  public static KycVerifSdkResult process(KYC_VERIF_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_5((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes), true);
    return ret;
  }

  public static KycVerifSdkResult process(IntPtr encodedDataPtr, uint encodedDataSize) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_process__SWIG_6(encodedDataPtr, encodedDataSize), true);
    return ret;
  }

  public static int exifOrientation(IntPtr jpegMetaDataPtr, uint jpegMetaDataSize) {
    int ret = KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_exifOrientation(jpegMetaDataPtr, jpegMetaDataSize);
    return ret;
  }

  public static KycVerifSdkResult requestRuntimeLicenseKey(bool rawInsteadOfJSON) {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_0(rawInsteadOfJSON), true);
    return ret;
  }

  public static KycVerifSdkResult requestRuntimeLicenseKey() {
    KycVerifSdkResult ret = new KycVerifSdkResult(KYCDocumentsVerifSDKPINVOKE.KycVerifSdkEngine_requestRuntimeLicenseKey__SWIG_1(), true);
    return ret;
  }

}

}
