# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_KYCDocumentsVerifSDK', [dirname(__file__)])
        except ImportError:
            import _KYCDocumentsVerifSDK
            return _KYCDocumentsVerifSDK
        if fp is not None:
            try:
                _mod = imp.load_module('_KYCDocumentsVerifSDK', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _KYCDocumentsVerifSDK = swig_import_helper()
    del swig_import_helper
else:
    import _KYCDocumentsVerifSDK
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


KYC_VERIF_SDK_VERSION_MAJOR = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_VERSION_MAJOR
KYC_VERIF_SDK_VERSION_MINOR = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_VERSION_MINOR
KYC_VERIF_SDK_VERSION_MICRO = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_VERSION_MICRO
KYC_VERIF_SDK_IMAGE_TYPE_RGB24 = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_RGB24
KYC_VERIF_SDK_IMAGE_TYPE_RGBA32 = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_RGBA32
KYC_VERIF_SDK_IMAGE_TYPE_BGRA32 = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_BGRA32
KYC_VERIF_SDK_IMAGE_TYPE_BGR24 = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_BGR24
KYC_VERIF_SDK_IMAGE_TYPE_NV12 = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_NV12
KYC_VERIF_SDK_IMAGE_TYPE_NV21 = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_NV21
KYC_VERIF_SDK_IMAGE_TYPE_YUV420P = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_YUV420P
KYC_VERIF_SDK_IMAGE_TYPE_YVU420P = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_YVU420P
KYC_VERIF_SDK_IMAGE_TYPE_YUV422P = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_YUV422P
KYC_VERIF_SDK_IMAGE_TYPE_YUV444P = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_YUV444P
KYC_VERIF_SDK_IMAGE_TYPE_Y = _KYCDocumentsVerifSDK.KYC_VERIF_SDK_IMAGE_TYPE_Y
class KycVerifSdkResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KycVerifSdkResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KycVerifSdkResult, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _KYCDocumentsVerifSDK.new_KycVerifSdkResult(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _KYCDocumentsVerifSDK.delete_KycVerifSdkResult
    __del__ = lambda self : None;
    def code(self): return _KYCDocumentsVerifSDK.KycVerifSdkResult_code(self)
    def phrase(self): return _KYCDocumentsVerifSDK.KycVerifSdkResult_phrase(self)
    def json(self): return _KYCDocumentsVerifSDK.KycVerifSdkResult_json(self)
    def numVIZs(self): return _KYCDocumentsVerifSDK.KycVerifSdkResult_numVIZs(self)
    def isOK(self): return _KYCDocumentsVerifSDK.KycVerifSdkResult_isOK(self)
KycVerifSdkResult_swigregister = _KYCDocumentsVerifSDK.KycVerifSdkResult_swigregister
KycVerifSdkResult_swigregister(KycVerifSdkResult)

class KycVerifSdkParallelDeliveryCallback(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KycVerifSdkParallelDeliveryCallback, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KycVerifSdkParallelDeliveryCallback, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _KYCDocumentsVerifSDK.delete_KycVerifSdkParallelDeliveryCallback
    __del__ = lambda self : None;
    def onNewResult(self, *args): return _KYCDocumentsVerifSDK.KycVerifSdkParallelDeliveryCallback_onNewResult(self, *args)
KycVerifSdkParallelDeliveryCallback_swigregister = _KYCDocumentsVerifSDK.KycVerifSdkParallelDeliveryCallback_swigregister
KycVerifSdkParallelDeliveryCallback_swigregister(KycVerifSdkParallelDeliveryCallback)

class KycVerifSdkEngine(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KycVerifSdkEngine, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KycVerifSdkEngine, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["init"] = lambda x: _KYCDocumentsVerifSDK.KycVerifSdkEngine_init
    if _newclass:init = staticmethod(_KYCDocumentsVerifSDK.KycVerifSdkEngine_init)
    __swig_getmethods__["deInit"] = lambda x: _KYCDocumentsVerifSDK.KycVerifSdkEngine_deInit
    if _newclass:deInit = staticmethod(_KYCDocumentsVerifSDK.KycVerifSdkEngine_deInit)
    __swig_getmethods__["process"] = lambda x: _KYCDocumentsVerifSDK.KycVerifSdkEngine_process
    if _newclass:process = staticmethod(_KYCDocumentsVerifSDK.KycVerifSdkEngine_process)
    __swig_getmethods__["exifOrientation"] = lambda x: _KYCDocumentsVerifSDK.KycVerifSdkEngine_exifOrientation
    if _newclass:exifOrientation = staticmethod(_KYCDocumentsVerifSDK.KycVerifSdkEngine_exifOrientation)
    __swig_getmethods__["requestRuntimeLicenseKey"] = lambda x: _KYCDocumentsVerifSDK.KycVerifSdkEngine_requestRuntimeLicenseKey
    if _newclass:requestRuntimeLicenseKey = staticmethod(_KYCDocumentsVerifSDK.KycVerifSdkEngine_requestRuntimeLicenseKey)
    __swig_destroy__ = _KYCDocumentsVerifSDK.delete_KycVerifSdkEngine
    __del__ = lambda self : None;
KycVerifSdkEngine_swigregister = _KYCDocumentsVerifSDK.KycVerifSdkEngine_swigregister
KycVerifSdkEngine_swigregister(KycVerifSdkEngine)

def KycVerifSdkEngine_init(*args):
  return _KYCDocumentsVerifSDK.KycVerifSdkEngine_init(*args)
KycVerifSdkEngine_init = _KYCDocumentsVerifSDK.KycVerifSdkEngine_init

def KycVerifSdkEngine_deInit():
  return _KYCDocumentsVerifSDK.KycVerifSdkEngine_deInit()
KycVerifSdkEngine_deInit = _KYCDocumentsVerifSDK.KycVerifSdkEngine_deInit

def KycVerifSdkEngine_process(*args):
  return _KYCDocumentsVerifSDK.KycVerifSdkEngine_process(*args)
KycVerifSdkEngine_process = _KYCDocumentsVerifSDK.KycVerifSdkEngine_process

def KycVerifSdkEngine_exifOrientation(*args):
  return _KYCDocumentsVerifSDK.KycVerifSdkEngine_exifOrientation(*args)
KycVerifSdkEngine_exifOrientation = _KYCDocumentsVerifSDK.KycVerifSdkEngine_exifOrientation

def KycVerifSdkEngine_requestRuntimeLicenseKey(rawInsteadOfJSON=False):
  return _KYCDocumentsVerifSDK.KycVerifSdkEngine_requestRuntimeLicenseKey(rawInsteadOfJSON)
KycVerifSdkEngine_requestRuntimeLicenseKey = _KYCDocumentsVerifSDK.KycVerifSdkEngine_requestRuntimeLicenseKey

# This file is compatible with both classic and new-style classes.


