/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.KycVerif.Sdk;

public class KycVerifSdkParallelDeliveryCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KycVerifSdkParallelDeliveryCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KycVerifSdkParallelDeliveryCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KYCDocumentsVerifSDKJNI.delete_KycVerifSdkParallelDeliveryCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void onNewResult(KycVerifSdkResult newResult) {
    KYCDocumentsVerifSDKJNI.KycVerifSdkParallelDeliveryCallback_onNewResult(swigCPtr, this, KycVerifSdkResult.getCPtr(newResult), newResult);
  }

}
